server:
  port: 8523
spring:
  servlet:
    multipart:
      enabled: true
        max-file-size: 1024MB
        max-request-size: 1024MB
  application:
    name: minioUtil
minio:
  endpoint: your-endpoint
  accessKey: your accessKey
  secretKey: your secretKey
  nginxHost: your nginxHost
